"""init

Revision ID: 0de71a60ca59
Revises: 
Create Date: 2025-08-13 23:38:48.051083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0de71a60ca59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.String(), nullable=False, comment='telegram id'),
    sa.Column('username', sa.String(), nullable=False, comment='telegram username'),
    sa.Column('first_name', sa.String(), nullable=True, comment='telegram first name'),
    sa.Column('last_name', sa.String(), nullable=True, comment='telegram last name'),
    sa.Column('dialogs_completed_today', sa.Integer(), nullable=True, comment='Количество завершенных диалогов сегодня'),
    sa.Column('dialogs_completed', sa.Integer(), nullable=True, comment='Количество завершенных диалогов за все время'),
    sa.Column('user_type', postgresql.ENUM('USER', 'ADMIN', name='user_type_enum'), nullable=False, comment='Тип пользователя'),
    sa.Column('subscription', postgresql.ENUM('FREE', 'DEFAULT', 'PRO', name='subscription_type_enum'), nullable=False, comment='Тип подписки пользователя'),
    sa.Column('subscription_date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_logging_requests',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('message', sa.String(), nullable=False, comment='Сообщение пользователя'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_logging_requests')
    op.drop_table('users')
    # ### end Alembic commands ###
