"""Add paymentlogs model

Revision ID: 6feb596e8f27
Revises: bf760bbe94b7
Create Date: 2025-08-22 15:00:56.548083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feb596e8f27'
down_revision = 'bf760bbe94b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentlogs',
    sa.Column('purchase_id', sa.String(), nullable=False, comment='ID Заказа'),
    sa.Column('telegram_id', sa.String(), nullable=False, comment='telegram id'),
    sa.Column('username', sa.String(), nullable=False, comment='telegram username'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='Цена за заказ'),
    sa.Column('month_sub', sa.Integer(), nullable=False, comment='Время подписки'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание заказа'),
    sa.Column('status', sa.String(), nullable=False, comment='Статус заказа'),
    sa.Column('link', sa.String(), nullable=False, comment='Ссылка для оплаты заказа'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Время покупки'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentlogs')
    # ### end Alembic commands ###
