"""fix_aye

Revision ID: c490fc76f3d0
Revises: 0de71a60ca59
Create Date: 2025-08-14 15:02:30.507722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c490fc76f3d0'
down_revision = '0de71a60ca59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_dialogs_logging',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('messages', postgresql.ARRAY(sa.VARCHAR()), nullable=False, comment='Массив сообщений пользователя'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_logging_requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_logging_requests',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='ID пользователя, совершившего запрос'),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Сообщение пользователя'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users_logging_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_logging_requests_pkey'))
    )
    op.drop_table('users_dialogs_logging')
    # ### end Alembic commands ###
